<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config = array(
	'cfg_site' => array(
			'standard_mall'	=>	'kor',
			'kor'	=> array(
				'title'	=> '몸캠피싱 해결 전문 기업, 아크링크(Arklink)',
				'nameKor'	=> '(주)아크링크',
				'nameEng'	=> 'ARKLINK',
				'adminEmail'	=> 'channel@arklink.co.kr',
				'compName'	=> '(주)아크링크',
				'item'	=> ' ',
				'service'	=> ' ',
				'zipcode'	=> ' ',
				'address'	=> '경기도 성남시 수정구 위례광장로 19, 제7층 제705호(창곡동, 아이페리온)',
				'ceoName'	=> '박민재',
				'compSerial'	=> '378-88-03382',
				'retailBusiness'	=> ' ',
				'adminName'	=> '박민재',
				'compPhone'	=> '1666-5706',
				'compFax'	=> ' ',
				'smsRecall'	=> ' ',
				'customerHour'	=> ' ',
			),
			'eng'	=> array(
				'title'	=> 'DesignArt1 ',
				'nameKor'	=> 'gabia ',
				'nameEng'	=> 'Gabia ',
				'adminEmail'	=> 'help@designart.co.kr',
				'compName'	=> 'dart',
				'item'	=> 'IT ',
				'service'	=> '디자인 ',
				'zipcode'	=> '000000 ',
				'address'	=> '4F, 660, Daewangpangyo-ro, Bundang-gu, Seongnam-si, Gyeonggi-do',
				'ceoName'	=> 'Hong Kuk Kim',
				'compSerial'	=> '214-86-3923 ',
				'retailBusiness'	=> '12345678 ',
				'adminName'	=> '홍길동 ',
				'compPhone'	=> '02-1544-3270 ',
				'compFax'	=> '02-1544-3270 ',
				'smsRecall'	=> '07000000000 ',
				'customerHour'	=> '평일 :AM 01:00 ~ PM 06:00<br>점심시간 :12:00 ~ 13:00 / 토,일,공휴일 휴무',
			),
			'chn'	=> array(
				'title'	=> '设计艺术1 ',
				'nameKor'	=> '智能传感器 ',
				'nameEng'	=> 'Gabia ',
				'adminEmail'	=> 'help@designart.co.kr',
				'compName'	=> 'D-设计艺术',
				'item'	=> 'IT ',
				'service'	=> '디자인 ',
				'zipcode'	=> '000000 ',
				'address'	=> '경기도 성남시 분당구 대왕판교로 660 4층 ',
				'ceoName'	=> '김홍국 ',
				'compSerial'	=> '214-86-3923 ',
				'retailBusiness'	=> '12345678 ',
				'adminName'	=> '홍길동 ',
				'compPhone'	=> '02-1544-3270 ',
				'compFax'	=> '02-1544-3270 ',
				'smsRecall'	=> '07000000000 ',
				'customerHour'	=> '평일 :AM 03:00 ~ PM 06:00<br>점심시간 :12:00 ~ 13:00 / 토,일,공휴일 휴무 ',
			),
			'jpn'	=> array(
				'title'	=> 'DesignArtJp1 ',
				'nameKor'	=> 'スマートセンサー ',
				'nameEng'	=> 'Gabia ',
				'adminEmail'	=> 'help@designart.co.kr',
				'compName'	=> 'D-デザインアーツ',
				'item'	=> 'IT ',
				'service'	=> '디자인 ',
				'zipcode'	=> '000000 ',
				'address'	=> '경기도 성남시 분당구 대왕판교로 660 4층 ',
				'ceoName'	=> '김홍국 ',
				'compSerial'	=> '214-86-3923 ',
				'retailBusiness'	=> '12345678 ',
				'adminName'	=> '홍길동 ',
				'compPhone'	=> '02-1544-3270 ',
				'compFax'	=> '02-1544-3270 ',
				'smsRecall'	=> '07000000000 ',
				'customerHour'	=> '평일 :AM 09:00 ~ PM 06:00<br>점심시간 :12:00 ~ 13:00 / 토,일,공휴일 휴무 ',
			),
		'seo' => array(
			'author'	=> '아크링크(Arklink)',
			'description'	=> '몸캠피싱 해결 전문 기업 아크링크(Arklink)입니다. 전문적인 인력과 기술력을 통해 피해 상황별 맞춤 솔루션을 적용해드리고 있습니다. 24시간 무료 상담을 통해 영상 유포 협박 상황을 해결하세요.',
			'keywords'	=> '몸캠피싱, 딥페이크, 연락처해킹, 몸캠피싱 해결, 몸캠피싱 무대응, 몸캠피싱 해킹, 악성 앱 분석, 영상유포차단, 몸캠피싱 협박',
			'snsTitle'	=> '아크링크(Arklink)',
			'snsDescription'	=> '몸캠피싱 해결 전문 기업 아크링크(Arklink)입니다. 전문적인 인력과 기술력을 통해 피해 상황별 맞춤 솔루션을 적용해드리고 있습니다. 24시간 무료 상담을 통해 영상 유포 협박 상황을 해결하세요.',
			'favicon'	=> 'garden_logo_R0c_icon.ico',
			'snsImage'	=> 'restmb_idxmake.jpg',
			'sitemap'	=> 'sitemap.xml',
		),
	),
);
