<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config = array(
	'memberField' => array(
		'name' => array(
			'kor'	=> array(
				'userid'	=> '아이디',
				'name'	=> '이름',
				'password'	=> '비밀번호',
				'level'	=> '등급',
				'group'	=> '그룹',
				'password_moddt'	=> '비밀번호변경일',
				'password_skip_cnt'	=> '다음에변경회수',
				'regdt'	=> '가입일',
				'last_login'	=> '최종접속일',
				'last_login_ip'	=> '접속아이피',
				'cnt_login'	=> '접속회수',
				'withdrawal_reason'	=> '회원탈퇴사유',
				'withdrawal_dt'	=> '회원탈퇴일',
				'yn_dormant_mail'	=> '휴면전환안내메일발송여부',
				'dormant_mail_dt'	=> '휴면전환안내메일발송일',
				'sex'	=> '성별',
				'birth'	=> '생년월일',
				'email'	=> '이메일',
				'zip'	=> '우편번호',
				'address'	=> '주소',
				'address2'	=> '상세주소',
				'mobile'	=> '연락처',
				'fax'	=> '팩스',
				'yn_mailling'	=> '메일수신',
				'yn_sms'	=> 'SMS수신',
				'ex1'	=> '예비 1 필수 테스트 ',
				'ex2'	=> '예비2',
				'ex3'	=> '예비3',
				'ex4'	=> '예비4',
				'ex5'	=> '예비5 한국어',
				'ex6'	=> '예비6',
				'ex7'	=> '예비7',
				'ex8'	=> '예비8',
				'ex9'	=> '예비9',
				'ex10'	=> '예비10',
				'ex11'	=> '예비11',
				'ex12'	=> '예비12',
				'ex13'	=> '예비13',
				'ex14'	=> '예비14',
				'ex15'	=> '예비15',
				'ex16'	=> '예비16',
				'ex17'	=> '32',
				'ex18'	=> '예비18',
				'ex19'	=> '국문 ',
				'ex20'	=> '예비20',
			),
			'eng'	=> array(
				'userid'	=> 'USER_ID',
				'name'	=> 'NAME1',
				'password'	=> 'PASSWORD',
				'level'	=> 'LEVEL',
				'group'	=> 'GROUP',
				'password_moddt'	=> 'PASSWORD_MODIFY_DATE',
				'password_skip_cnt'	=> 'PASSWORD_SKIP_COUNT',
				'regdt'	=> 'regdt',
				'last_login'	=> 'last_login',
				'last_login_ip'	=> 'last_login_ip',
				'cnt_login'	=> 'cnt_login',
				'withdrawal_reason'	=> 'withdrawal_reason',
				'withdrawal_dt'	=> 'withdrawal_dt',
				'yn_dormant_mail'	=> 'yn_dormant_mail',
				'dormant_mail_dt'	=> 'dormant_mail_dt',
				'sex'	=> 'SEX',
				'birth'	=> 'BIRTH',
				'email'	=> 'email',
				'zip'	=> 'zip',
				'address'	=> 'address',
				'address2'	=> 'address2',
				'mobile'	=> 'mobile',
				'fax'	=> 'fax',
				'yn_mailling'	=> 'yn_mailling',
				'yn_sms'	=> 'yn_sms',
				'ex1'	=> 'ㄴㄴ',
				'ex2'	=> '가입동기2',
				'ex3'	=> '취미',
				'ex4'	=> '특기',
				'ex5'	=> '예비5 영어 ',
				'ex6'	=> '모바일 추가항목2',
				'ex7'	=> '예비7',
				'ex8'	=> '예비8',
				'ex9'	=> '예비9',
				'ex10'	=> '예비10',
				'ex11'	=> '예비11',
				'ex12'	=> '예비12',
				'ex13'	=> '예비13',
				'ex14'	=> '예비14',
				'ex15'	=> '예비15',
				'ex16'	=> '예비16',
				'ex17'	=> '예비17',
				'ex18'	=> '예비18',
				'ex19'	=> '영문 ',
				'ex20'	=> '예비20',
			),
			'chn'	=> array(
				'userid'	=> '账号',
				'name'	=> '姓名',
				'password'	=> '密码',
				'level'	=> '等级',
				'group'	=> '集团',
				'password_moddt'	=> '密码变更日期',
				'password_skip_cnt'	=> '密码变更次数',
				'regdt'	=> '加入日',
				'last_login'	=> '最终连接日期',
				'last_login_ip'	=> '访问IP',
				'cnt_login'	=> '访问次数',
				'withdrawal_reason'	=> '理由注销会员',
				'withdrawal_dt'	=> '会员处理日',
				'yn_dormant_mail'	=> '是否发送休眠转换指南邮件',
				'dormant_mail_dt'	=> '休眠转换通知邮件发送日期',
				'sex'	=> '性别',
				'birth'	=> '出生年月日',
				'email'	=> '电子邮件',
				'zip'	=> '邮政编码',
				'address'	=> '住址',
				'address2'	=> '详细地址',
				'mobile'	=> '联络处',
				'fax'	=> '传真',
				'yn_mailling'	=> '邮件收发',
				'yn_sms'	=> '短信收信',
				'ex1'	=> 'ㅇㅇㅇ',
				'ex2'	=> 'ㅇㅇㅇㅇ',
				'ex3'	=> 'ㅁㅁㅁ',
				'ex4'	=> 'ㅁㅁㅁ',
				'ex5'	=> '예비5 중국어 ',
				'ex6'	=> '',
				'ex7'	=> '',
				'ex8'	=> '',
				'ex9'	=> '',
				'ex10'	=> '',
				'ex11'	=> '',
				'ex12'	=> '',
				'ex13'	=> '',
				'ex14'	=> '',
				'ex15'	=> '',
				'ex16'	=> '',
				'ex17'	=> 'ㅁㅁㅁㅁㄹㄹㄹ',
				'ex18'	=> '',
				'ex19'	=> '',
				'ex20'	=> 'ㅋㅋ',
			),
			'jpn'	=> array(
				'userid'	=> 'ハンドルネーム',
				'name'	=> '名前',
				'password'	=> 'パスワード',
				'level'	=> '等級',
				'group'	=> 'グループ',
				'password_moddt'	=> '暗証番号変更日',
				'password_skip_cnt'	=> '',
				'regdt'	=> '',
				'last_login'	=> '',
				'last_login_ip'	=> '',
				'cnt_login'	=> '',
				'withdrawal_reason'	=> '',
				'withdrawal_dt'	=> '',
				'yn_dormant_mail'	=> '',
				'dormant_mail_dt'	=> '',
				'sex'	=> '性別',
				'birth'	=> '生年月日',
				'email'	=> 'Eメール',
				'zip'	=> '郵便番号',
				'address'	=> 'アドレス',
				'address2'	=> '',
				'mobile'	=> '',
				'fax'	=> '',
				'yn_mailling'	=> '',
				'yn_sms'	=> '',
				'ex1'	=> '',
				'ex2'	=> '',
				'ex3'	=> '',
				'ex4'	=> '',
				'ex5'	=> '',
				'ex6'	=> '',
				'ex7'	=> '',
				'ex8'	=> '',
				'ex9'	=> '',
				'ex10'	=> '',
				'ex11'	=> '',
				'ex12'	=> '',
				'ex13'	=> '',
				'ex14'	=> '',
				'ex15'	=> '',
				'ex16'	=> '',
				'ex17'	=> '',
				'ex18'	=> '',
				'ex19'	=> '',
				'ex20'	=> 'ㅋㅋㅋ',
			),
		),
		'use' => array(
			'birth'	=> 'checked',
			'email'	=> 'checked',
			'zip'	=> 'checked',
			'address'	=> 'checked',
			'fax'	=> 'checked',
			'yn_mailling'	=> 'checked',
			'yn_sms'	=> 'checked',
			'ex1'	=> 'checked',
			'ex5'	=> 'checked',
			'ex19'	=> 'checked',
		),
		'require' => array(
			'birth'	=> 'checked',
			'email'	=> 'checked',
			'zip'	=> 'checked',
			'address'	=> 'checked',
			'address2'	=> 'checked',
			'mobile'	=> 'checked',
			'fax'	=> 'checked',
			'yn_mailling'	=> 'checked',
			'yn_sms'	=> 'checked',
			'ex1'	=> 'checked',
			'ex17'	=> 'checked',
		),
		'type' => array(
			'sex'	=> 'radio',
			'birth'	=> 'text',
			'email'	=> 'email',
			'zip'	=> 'text',
			'address'	=> 'text',
			'address2'	=> 'text',
			'mobile'	=> 'text',
			'fax'	=> 'text',
			'yn_mailling'	=> 'radio',
			'yn_sms'	=> 'radio',
			'ex1'	=> 'text',
			'ex2'	=> 'select',
			'ex3'	=> 'email',
			'ex4'	=> 'text',
			'ex5'	=> 'text',
			'ex6'	=> 'select',
			'ex7'	=> 'radio',
			'ex8'	=> 'select',
			'ex9'	=> 'text',
			'ex10'	=> 'text',
			'ex11'	=> 'text',
			'ex12'	=> 'text',
			'ex13'	=> 'text',
			'ex14'	=> 'text',
			'ex15'	=> 'text',
			'ex16'	=> 'text',
			'ex17'	=> 'text',
			'ex18'	=> 'text',
			'ex19'	=> 'text',
			'ex20'	=> 'text',
		),
		'option' => array(
			'sex'	=> array(
				'item'	=> array(
					'kor'	=> array(
					'm'	=> '남자',
					'f'	=> '여자',
					),
					'eng'	=> array(
					'm'	=> 'man',
					'f'	=> 'woman',
					),
					'chn'	=> array(
					'm'	=> 'man',
					'f'	=> 'woman',
					),
					'jpn'	=> array(
					'm'	=> 'man',
					'f'	=> 'woman',
					),
				),
			),
			'email'	=> array(
				'item'	=> array(
					'kor'	=> array(
					'email-1'	=> '직접입력',
					'email-2'	=> 'daum.net',
					'email-3'	=> 'naver.com',
					'email-4'	=> 'yahoo.com',
					'email-5'	=> 'gmail.com',
					),
					'eng'	=> array(
					'email-1'	=> '',
					'email-2'	=> 'google.com',
					'email-3'	=> 'naver.com',
					),
				),
			),
			'yn_mailling'	=> array(
				'item'	=> array(
					'kor'	=> array(
					'y'	=> '수신동의',
					'n'	=> '수신거부',
					),
					'eng'	=> array(
					'y'	=> 'Y',
					'n'	=> 'N',
					),
					'chn'	=> array(
					'y'	=> 'Y',
					'n'	=> 'N',
					),
					'jpn'	=> array(
					'y'	=> '受信同意',
					'n'	=> '受信拒否',
					),
				),
			),
			'yn_sms'	=> array(
				'item'	=> array(
					'kor'	=> array(
					'y'	=> '수신동의',
					'n'	=> '수신거부',
					),
					'eng'	=> array(
					'y'	=> 'Y',
					'n'	=> 'N',
					),
					'chn'	=> array(
					'y'	=> 'Y',
					'n'	=> 'N',
					),
					'jpn'	=> array(
					'y'	=> '受信同意',
					'n'	=> '受信拒否',
					),
				),
			),
			'ex1'	=> array(
				'item'	=> array(
					'eng'	=> array(
					'ex1-1'	=> '1',
					),
					'kor'	=> array(
					'ex1-1'	=> '2',
					'ex1-2'	=> '3',
					),
				),
			),
			'ex2'	=> array(
				'item'	=> array(
					'kor'	=> array(
					'ex2-1'	=> 'test2',
					'ex2-2'	=> 'test1',
					'ex2-3'	=> 'test3',
					),
				),
			),
			'ex3'	=> array(
				'item'	=> array(
					'kor'	=> array(
					'ex3-1'	=> 'dddd',
					),
				),
			),
			'ex5'	=> array(
				'item'	=> array(
					'eng'	=> array(
					'ex5-1'	=> '2',
					),
					'chn'	=> array(
					'ex5-1'	=> '4',
					),
				),
			),
		),
	),
);
